### ISSUE TITLE
Deployment guide feedback

### ISSUE THREAD

**Issue by g8rl0ki** [aws-ia/cfn-ps-cisco-duo-network-gateway#8]
Section heading:
Documentation issue description:
cf deployment fails on an s3 error, after troubleshooting I discovered this link is invalid: https://aws-ia-us-east-1.s3.us-east-1.amazonaws.com/cfn-ps-cisco-duo-network-gateway/submodules/cfn-ps-aws-acm-certificate/templates/quickstart-aws-acm-certificate.template.yml

This is referenced by [https://aws-ia-us-east-1.s3.us-east-1.amazonaws.com/cfn-ps-cisco-duo-network-gateway/templates/qui[…]uo-network-gateway-portal-servers.template.yaml](https://aws-ia-us-east-1.s3.us-east-1.amazonaws.com/cfn-ps-cisco-duo-network-gateway/templates/qui[%E2%80%A6]uo-network-gateway-portal-servers.template.yaml) and https://aws-ia-us-east-1.s3.us-east-1.amazonaws.com/cfn-ps-cisco-duo-network-gateway/templates/admin-server.template.yaml

**Comment by mufaddalq** [comment]
This should be resolved in https://github.com/aws-ia/cfn-ps-cisco-duo-network-gateway/pull/18

**Comment by opavlyshyn** [comment]
Hello @mufaddalq!

Seems like this issue is not fixed for now. I got Stack failure and `Access Denied` after downloading of `quickstart-aws-acm-certificate.template.yml` directly.(see attachment) 
But others .yml files I was able to download via https from the bucket directly as well.(see attachment)
<img width="1371" alt="image" src="https://github.com/aws-ia/cfn-ps-cisco-duo-network-gateway/assets/79916699/4d3c30cd-5429-4579-9ec5-9d3412b62fb6">
<img width="1728" alt="image" src="https://github.com/aws-ia/cfn-ps-cisco-duo-network-gateway/assets/79916699/5f6a7019-0fe0-4075-bd14-16d74823765f">
<img width="782" alt="image" src="https://github.com/aws-ia/cfn-ps-cisco-duo-network-gateway/assets/79916699/0e89999a-4d14-442f-99af-352fca270450">


Also, I guess we need to merge old fixed form the https://github.com/aws-quickstart/quickstart-cisco-duo-network-gateway, that I made some time before.

Please let me know if u need smth from my side, I'm glad to support u if needed.

**Comment by g8rl0ki** [comment]
Same, I'm still getting access denied. Can we get the priority of this bumped up? this has been broken for over 6 months.

**Comment by opavlyshyn** [comment]
@mufaddalq we should probably merge previous changes - https://github.com/aws-quickstart/quickstart-cisco-duo-network-gateway/pull/23(added to archived repo - https://github.com/aws-quickstart/quickstart-cisco-duo-network-gateway)

**Comment by opavlyshyn** [comment]
@mufaddalq have u had a chance to take a look at it?)
